# Generated by Django 4.1.1 on 2022-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMarca', models.CharField(help_text='Decriccion', max_length=300)),
                ('codigoMarca', models.CharField(help_text='Decriccion', max_length=10)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marca',
            },
        ),
    ]
