# Generated by Django 4.1.1 on 2022-09-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculaCoche', models.CharField(help_text='Ingrese el Matricula ', max_length=8)),
                ('nodeloCoche', models.CharField(help_text='Ingrese el Modelo ', max_length=100)),
                ('colorCoche', models.CharField(help_text='Ingrese el Color', max_length=100)),
                ('pvcCoche', models.CharField(help_text='Ingrese el PVC', max_length=100)),
                ('codigoMarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.marca')),
                ('nitCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'coche',
                'verbose_name_plural': 'coche',
            },
        ),
    ]
