# Generated by Django 4.1.1 on 2022-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitCliente', models.CharField(help_text='Ingrese el Nit del Cliente', max_length=20)),
                ('nombreCliente', models.CharField(help_text='Ingrese el Nombre del Cliente', max_length=100)),
                ('apellidoCliente', models.CharField(help_text='Ingrese el apellido del Cliente', max_length=100)),
                ('direccionCliente', models.CharField(help_text='Ingrese la Direccion del Cliente', max_length=100)),
                ('ciudadCliente', models.CharField(help_text='Ingrese el ciudad del Cliente', max_length=100)),
                ('correoCliente', models.EmailField(help_text='Ingrese el Correo del Cliente', max_length=100)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
